-- MySQL dump 10.13  Distrib 5.6.39, for Linux (x86_64)
--
-- Host: localhost    Database: sprint1
-- ------------------------------------------------------
-- Server version	5.6.39-cll-lve

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `checkbox-values`
--

DROP TABLE IF EXISTS `checkbox-values`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `checkbox-values` (
  `id` int(11) NOT NULL,
  `name` varchar(500) DEFAULT NULL,
  `sectionID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDsection_idx` (`sectionID`),
  CONSTRAINT `IDsection` FOREIGN KEY (`sectionID`) REFERENCES `section_checkbox` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `checkbox-values`
--

LOCK TABLES `checkbox-values` WRITE;
/*!40000 ALTER TABLE `checkbox-values` DISABLE KEYS */;
INSERT INTO `checkbox-values` (`id`, `name`, `sectionID`) VALUES (1,'CSS applied, responsive design',1),(2,'Browser support, IE 11 included',1),(3,'Confluence documentation (cross-concepts, complex logic, workflow, and dev machine setup)',1),(4,'Swagger documentation',1),(5,'Merged to dev branch (ng lint, test, run)',2),(6,'Works on Apache: int-acc-fut-evew',2),(7,'Works on AEM preview mode: int-acc-fut-evcms',2),(8,'Content (lables, snippets, svg) loaded from CMS-AEM',2),(9,'Middleware Calvin/ESB data should be used (if not explicitly agreed with PO/TO to use mock)',2),(10,'Via the HTML (generated by CMS) page web app ui:verify implemented requirements',2),(11,'Software build must not fail (automated tests, compile errors, green sonar, codig guidelines, formatting rules)',3),(12,'No JS: network errors, warnings, infos in browser-console at runtime',3),(13,'Reviewed and tested by 3rd party, person who didn\'t work on the task',4),(14,'Unit test coverage is fullfiled (backend, frontend)',4),(15,'Defects in acceptable state to the product owner',4);
/*!40000 ALTER TABLE `checkbox-values` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `frontend_values`
--

DROP TABLE IF EXISTS `frontend_values`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `frontend_values` (
  `id` int(11) NOT NULL,
  `checked` tinyint(1) DEFAULT NULL,
  `checkbox_valuesID` int(11) DEFAULT NULL,
  `taskID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDcheckbox_values_idx` (`checkbox_valuesID`),
  KEY `IDtask_idx` (`taskID`),
  CONSTRAINT `IDcheckbox_values` FOREIGN KEY (`checkbox_valuesID`) REFERENCES `checkbox-values` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `IDtask` FOREIGN KEY (`taskID`) REFERENCES `task` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `frontend_values`
--

LOCK TABLES `frontend_values` WRITE;
/*!40000 ALTER TABLE `frontend_values` DISABLE KEYS */;
INSERT INTO `frontend_values` (`id`, `checked`, `checkbox_valuesID`, `taskID`) VALUES (1,0,1,1),(2,0,2,1),(3,0,3,1),(4,0,4,1),(5,0,5,1),(6,0,6,1),(7,0,7,1),(8,1,8,1),(9,1,9,1),(10,1,10,1),(11,0,11,1),(12,0,12,1),(13,0,13,1),(14,0,14,1),(15,0,15,1);
/*!40000 ALTER TABLE `frontend_values` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `person`
--

DROP TABLE IF EXISTS `person`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `person` (
  `id` int(11) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `lastname` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `person`
--

LOCK TABLES `person` WRITE;
/*!40000 ALTER TABLE `person` DISABLE KEYS */;
INSERT INTO `person` (`id`, `name`, `lastname`) VALUES (1,'Vedran','Bojanic'),(2,'Renato','Curic'),(3,'Tomislav','Gajsak'),(4,'Luka','Leovac'),(5,'Franjo','Pozaic'),(6,'Marko','Previsic'),(7,'Petar','Prole'),(8,'Eugen','Sunic'),(9,'xx','xx');
/*!40000 ALTER TABLE `person` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `section_checkbox`
--

DROP TABLE IF EXISTS `section_checkbox`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `section_checkbox` (
  `id` int(11) NOT NULL,
  `section` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `section_checkbox`
--

LOCK TABLES `section_checkbox` WRITE;
/*!40000 ALTER TABLE `section_checkbox` DISABLE KEYS */;
INSERT INTO `section_checkbox` (`id`, `section`) VALUES (1,'section1'),(2,'section2'),(3,'section3'),(4,'section4');
/*!40000 ALTER TABLE `section_checkbox` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `sprint`
--

DROP TABLE IF EXISTS `sprint`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sprint` (
  `id` int(11) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `duration` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `sprint`
--

LOCK TABLES `sprint` WRITE;
/*!40000 ALTER TABLE `sprint` DISABLE KEYS */;
INSERT INTO `sprint` (`id`, `name`, `duration`) VALUES (5,'Sprint 5','15.10-20.10'),(6,'Sprint 6','');
/*!40000 ALTER TABLE `sprint` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `task`
--

DROP TABLE IF EXISTS `task`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `task` (
  `id` int(11) NOT NULL,
  `name` varchar(250) DEFAULT NULL,
  `url` varchar(500) DEFAULT NULL,
  `sprintID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDsprint_idx` (`sprintID`),
  CONSTRAINT `IDsprint` FOREIGN KEY (`sprintID`) REFERENCES `sprint` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `task`
--

LOCK TABLES `task` WRITE;
/*!40000 ALTER TABLE `task` DISABLE KEYS */;
INSERT INTO `task` (`id`, `name`, `url`, `sprintID`) VALUES (1,'ITWEMO-248-preview-mode','http://www.google.com',5),(2,'ITWEMO-122-churchtax','0',5),(3,'ITWEMO-130-springboot','0',5),(4,'ITWEMO-222-nashvile','0',5);
/*!40000 ALTER TABLE `task` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `time`
--

DROP TABLE IF EXISTS `time`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `time` (
  `id` int(11) NOT NULL,
  `value` datetime DEFAULT NULL,
  `taskID` int(11) DEFAULT NULL,
  `personID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDtask1_idx` (`taskID`),
  KEY `IDperson_idx` (`personID`),
  CONSTRAINT `IDperson` FOREIGN KEY (`personID`) REFERENCES `person` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `IDtask1` FOREIGN KEY (`taskID`) REFERENCES `task` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `time`
--

LOCK TABLES `time` WRITE;
/*!40000 ALTER TABLE `time` DISABLE KEYS */;
INSERT INTO `time` (`id`, `value`, `taskID`, `personID`) VALUES (1,NULL,1,1);
/*!40000 ALTER TABLE `time` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping events for database 'sprint1'
--

--
-- Dumping routines for database 'sprint1'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-05-04 12:17:31
